// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdxQVetEBEz52r64dHh91BVzrrpVH1ez4',
    appId: '1:183687643642:web:7e6f62fb4fce4aff76a443',
    messagingSenderId: '183687643642',
    projectId: 'gradingapp-30882',
    authDomain: 'gradingapp-30882.firebaseapp.com',
    storageBucket: 'gradingapp-30882.firebasestorage.app',
    measurementId: 'G-WF75NRDPHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5QZQuDElCxux4ickZmY3P3zM-qnAahFE',
    appId: '1:183687643642:android:845522220e4e42f276a443',
    messagingSenderId: '183687643642',
    projectId: 'gradingapp-30882',
    storageBucket: 'gradingapp-30882.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdxQVetEBEz52r64dHh91BVzrrpVH1ez4',
    appId: '1:183687643642:web:6d86a96a0b82f4b876a443',
    messagingSenderId: '183687643642',
    projectId: 'gradingapp-30882',
    authDomain: 'gradingapp-30882.firebaseapp.com',
    storageBucket: 'gradingapp-30882.firebasestorage.app',
    measurementId: 'G-STR6CED8XH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuF9PrhWtlhNMiMLrUE52ZZ9tr2PNbhHE',
    appId: '1:183687643642:ios:0452afe7c6a16dc576a443',
    messagingSenderId: '183687643642',
    projectId: 'gradingapp-30882',
    storageBucket: 'gradingapp-30882.firebasestorage.app',
    iosBundleId: 'com.example.gradingapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuF9PrhWtlhNMiMLrUE52ZZ9tr2PNbhHE',
    appId: '1:183687643642:ios:0452afe7c6a16dc576a443',
    messagingSenderId: '183687643642',
    projectId: 'gradingapp-30882',
    storageBucket: 'gradingapp-30882.firebasestorage.app',
    iosBundleId: 'com.example.gradingapp',
  );

}